# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desinge_my_project1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 500, 600))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.started_page = QtWidgets.QWidget()
        self.started_page.setObjectName("started_page")
        self.start = QtWidgets.QPushButton(self.started_page)
        self.start.setGeometry(QtCore.QRect(150, 440, 200, 70))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.start.setAutoDefault(False)
        self.start.setObjectName("start")
        self.about_pr = QtWidgets.QPushButton(self.started_page)
        self.about_pr.setGeometry(QtCore.QRect(150, 520, 200, 70))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.about_pr.setFont(font)
        self.about_pr.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"    border:5px solid #aa8925\n"
"}")
        self.about_pr.setObjectName("about_pr")
        self.line_on_start_window = QtWidgets.QFrame(self.started_page)
        self.line_on_start_window.setGeometry(QtCore.QRect(0, 420, 500, 16))
        self.line_on_start_window.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_on_start_window.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_on_start_window.setObjectName("line_on_start_window")
        self.take_off_button_on_start_pg = QtWidgets.QPushButton(self.started_page)
        self.take_off_button_on_start_pg.setGeometry(QtCore.QRect(430, 530, 61, 61))
        self.take_off_button_on_start_pg.setStyleSheet("border:5px solid rgb(170, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 30px;")
        self.take_off_button_on_start_pg.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/take_off_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.take_off_button_on_start_pg.setIcon(icon)
        self.take_off_button_on_start_pg.setIconSize(QtCore.QSize(61, 61))
        self.take_off_button_on_start_pg.setObjectName("take_off_button_on_start_pg")
        self.frame = QtWidgets.QFrame(self.started_page)
        self.frame.setGeometry(QtCore.QRect(40, 10, 421, 51))
        self.frame.setStyleSheet("background-color: rgb(202, 67, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(202, 67, 0);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_on_tasks_2 = QtWidgets.QLabel(self.started_page)
        self.label_on_tasks_2.setGeometry(QtCore.QRect(10, 170, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks_2.setFont(font)
        self.label_on_tasks_2.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks_2.setObjectName("label_on_tasks_2")
        self.label_on_tasks_3 = QtWidgets.QLabel(self.started_page)
        self.label_on_tasks_3.setGeometry(QtCore.QRect(220, 170, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks_3.setFont(font)
        self.label_on_tasks_3.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks_3.setText("")
        self.label_on_tasks_3.setObjectName("label_on_tasks_3")
        self.label_on_tasks_4 = QtWidgets.QLabel(self.started_page)
        self.label_on_tasks_4.setGeometry(QtCore.QRect(10, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks_4.setFont(font)
        self.label_on_tasks_4.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks_4.setObjectName("label_on_tasks_4")
        self.label_on_tasks_5 = QtWidgets.QLabel(self.started_page)
        self.label_on_tasks_5.setGeometry(QtCore.QRect(110, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks_5.setFont(font)
        self.label_on_tasks_5.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks_5.setText("")
        self.label_on_tasks_5.setObjectName("label_on_tasks_5")
        self.label_on_tasks_6 = QtWidgets.QLabel(self.started_page)
        self.label_on_tasks_6.setGeometry(QtCore.QRect(10, 70, 185, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks_6.setFont(font)
        self.label_on_tasks_6.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks_6.setObjectName("label_on_tasks_6")
        self.clock_picture = QtWidgets.QLabel(self.started_page)
        self.clock_picture.setGeometry(QtCore.QRect(150, 220, 201, 201))
        self.clock_picture.setText("")
        self.clock_picture.setPixmap(QtGui.QPixmap("pictures/clock2.png"))
        self.clock_picture.setObjectName("clock_picture")
        self.label_on_tasks_7 = QtWidgets.QLabel(self.started_page)
        self.label_on_tasks_7.setGeometry(QtCore.QRect(200, 70, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks_7.setFont(font)
        self.label_on_tasks_7.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks_7.setText("")
        self.label_on_tasks_7.setObjectName("label_on_tasks_7")
        self.stackedWidget.addWidget(self.started_page)
        self.tasks = QtWidgets.QWidget()
        self.tasks.setObjectName("tasks")
        self.back_button_on_tasks = QtWidgets.QPushButton(self.tasks)
        self.back_button_on_tasks.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.back_button_on_tasks.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.back_button_on_tasks.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pictures/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button_on_tasks.setIcon(icon1)
        self.back_button_on_tasks.setIconSize(QtCore.QSize(40, 35))
        self.back_button_on_tasks.setObjectName("back_button_on_tasks")
        self.home_button_on_tasks = QtWidgets.QPushButton(self.tasks)
        self.home_button_on_tasks.setGeometry(QtCore.QRect(70, 10, 51, 41))
        self.home_button_on_tasks.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.home_button_on_tasks.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pictures/house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button_on_tasks.setIcon(icon2)
        self.home_button_on_tasks.setIconSize(QtCore.QSize(50, 50))
        self.home_button_on_tasks.setObjectName("home_button_on_tasks")
        self.label_on_tasks = QtWidgets.QLabel(self.tasks)
        self.label_on_tasks.setGeometry(QtCore.QRect(190, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_on_tasks.setFont(font)
        self.label_on_tasks.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_on_tasks.setObjectName("label_on_tasks")
        self.pushButton_save_task = QtWidgets.QPushButton(self.tasks)
        self.pushButton_save_task.setGeometry(QtCore.QRect(20, 550, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_save_task.setFont(font)
        self.pushButton_save_task.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_save_task.setObjectName("pushButton_save_task")
        self.pushButton_load_task = QtWidgets.QPushButton(self.tasks)
        self.pushButton_load_task.setGeometry(QtCore.QRect(370, 550, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_load_task.setFont(font)
        self.pushButton_load_task.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_load_task.setObjectName("pushButton_load_task")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tasks)
        self.textEdit_2.setGeometry(QtCore.QRect(13, 60, 471, 481))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color:  rgb(53, 59, 83);\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_clear_task = QtWidgets.QPushButton(self.tasks)
        self.pushButton_clear_task.setGeometry(QtCore.QRect(200, 550, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_clear_task.setFont(font)
        self.pushButton_clear_task.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_clear_task.setObjectName("pushButton_clear_task")
        self.stackedWidget.addWidget(self.tasks)
        self.another_time_2 = QtWidgets.QWidget()
        self.another_time_2.setObjectName("another_time_2")
        self.comboBox_city = QtWidgets.QComboBox(self.another_time_2)
        self.comboBox_city.setGeometry(QtCore.QRect(10, 110, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.comboBox_city.setFont(font)
        self.comboBox_city.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    \n"
"    background-color: rgb(255, 203, 97);\n"
"}\n"
"\n"
"\n"
"")
        self.comboBox_city.setObjectName("comboBox_city")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.label_12 = QtWidgets.QLabel(self.another_time_2)
        self.label_12.setGeometry(QtCore.QRect(50, 60, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_12.setObjectName("label_12")
        self.back_another_time = QtWidgets.QPushButton(self.another_time_2)
        self.back_another_time.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.back_another_time.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.back_another_time.setText("")
        self.back_another_time.setIcon(icon1)
        self.back_another_time.setIconSize(QtCore.QSize(40, 35))
        self.back_another_time.setObjectName("back_another_time")
        self.home_another_time = QtWidgets.QPushButton(self.another_time_2)
        self.home_another_time.setGeometry(QtCore.QRect(70, 10, 51, 41))
        self.home_another_time.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.home_another_time.setText("")
        self.home_another_time.setIcon(icon2)
        self.home_another_time.setIconSize(QtCore.QSize(50, 50))
        self.home_another_time.setObjectName("home_another_time")
        self.label_13 = QtWidgets.QLabel(self.another_time_2)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 230, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.another_time_2)
        self.label_14.setGeometry(QtCore.QRect(10, 270, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.another_time_2)
        self.label_15.setGeometry(QtCore.QRect(10, 340, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_15.setObjectName("label_15")
        self.line_2 = QtWidgets.QFrame(self.another_time_2)
        self.line_2.setGeometry(QtCore.QRect(250, 180, 31, 211))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_day_another_time = QtWidgets.QLabel(self.another_time_2)
        self.label_day_another_time.setGeometry(QtCore.QRect(290, 200, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_day_another_time.setFont(font)
        self.label_day_another_time.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_day_another_time.setText("")
        self.label_day_another_time.setObjectName("label_day_another_time")
        self.label_date_another_time = QtWidgets.QLabel(self.another_time_2)
        self.label_date_another_time.setGeometry(QtCore.QRect(290, 270, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_date_another_time.setFont(font)
        self.label_date_another_time.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_date_another_time.setText("")
        self.label_date_another_time.setObjectName("label_date_another_time")
        self.label_time_another_time = QtWidgets.QLabel(self.another_time_2)
        self.label_time_another_time.setGeometry(QtCore.QRect(290, 340, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_time_another_time.setFont(font)
        self.label_time_another_time.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_time_another_time.setText("")
        self.label_time_another_time.setObjectName("label_time_another_time")
        self.stackedWidget.addWidget(self.another_time_2)
        self.timer = QtWidgets.QWidget()
        self.timer.setObjectName("timer")
        self.spinBox = QtWidgets.QSpinBox(self.timer)
        self.spinBox.setGeometry(QtCore.QRect(240, 290, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("color: rgb(143, 128, 254);\n"
"border:5px solid  rgb(0, 170, 127);\n"
"")
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.timer)
        self.spinBox_2.setGeometry(QtCore.QRect(240, 360, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("color: rgb(143, 128, 254);\n"
"border:5px solid  rgb(0, 170, 127);")
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.timer)
        self.spinBox_3.setGeometry(QtCore.QRect(240, 430, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("color: rgb(143, 128, 254);\n"
"border:5px solid  rgb(0, 170, 127);")
        self.spinBox_3.setObjectName("spinBox_3")
        self.label = QtWidgets.QLabel(self.timer)
        self.label.setGeometry(QtCore.QRect(20, 290, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(60, 75, 127);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.timer)
        self.label_3.setGeometry(QtCore.QRect(20, 360, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(60, 75, 127);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.timer)
        self.label_4.setGeometry(QtCore.QRect(20, 430, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(60, 75, 127);")
        self.label_4.setObjectName("label_4")
        self.pushButton_home_timer = QtWidgets.QPushButton(self.timer)
        self.pushButton_home_timer.setGeometry(QtCore.QRect(70, 10, 51, 41))
        self.pushButton_home_timer.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_home_timer.setText("")
        self.pushButton_home_timer.setIcon(icon2)
        self.pushButton_home_timer.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_home_timer.setObjectName("pushButton_home_timer")
        self.pushButton_start_timer = QtWidgets.QPushButton(self.timer)
        self.pushButton_start_timer.setGeometry(QtCore.QRect(30, 530, 140, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_start_timer.setFont(font)
        self.pushButton_start_timer.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_start_timer.setObjectName("pushButton_start_timer")
        self.pushButton_restart_timer = QtWidgets.QPushButton(self.timer)
        self.pushButton_restart_timer.setGeometry(QtCore.QRect(330, 530, 140, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_restart_timer.setFont(font)
        self.pushButton_restart_timer.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}\n"
"")
        self.pushButton_restart_timer.setObjectName("pushButton_restart_timer")
        self.line = QtWidgets.QFrame(self.timer)
        self.line.setGeometry(QtCore.QRect(0, 500, 500, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_timer_label = QtWidgets.QLabel(self.timer)
        self.label_timer_label.setGeometry(QtCore.QRect(60, 60, 381, 160))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(72)
        self.label_timer_label.setFont(font)
        self.label_timer_label.setStyleSheet("background-color: rgb(53, 59, 83);")
        self.label_timer_label.setObjectName("label_timer_label")
        self.pushButton_back_timer = QtWidgets.QPushButton(self.timer)
        self.pushButton_back_timer.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.pushButton_back_timer.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_back_timer.setText("")
        self.pushButton_back_timer.setIcon(icon1)
        self.pushButton_back_timer.setIconSize(QtCore.QSize(40, 35))
        self.pushButton_back_timer.setObjectName("pushButton_back_timer")
        self.pushButton_stop_timer = QtWidgets.QPushButton(self.timer)
        self.pushButton_stop_timer.setGeometry(QtCore.QRect(180, 530, 140, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_stop_timer.setFont(font)
        self.pushButton_stop_timer.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}\n"
"")
        self.pushButton_stop_timer.setObjectName("pushButton_stop_timer")
        self.label_timer = QtWidgets.QLabel(self.timer)
        self.label_timer.setGeometry(QtCore.QRect(195, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_timer.setFont(font)
        self.label_timer.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_timer.setObjectName("label_timer")
        self.stackedWidget.addWidget(self.timer)
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.alarm_clock_button = QtWidgets.QPushButton(self.menu)
        self.alarm_clock_button.setGeometry(QtCore.QRect(125, 60, 250, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.alarm_clock_button.setFont(font)
        self.alarm_clock_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.alarm_clock_button.setObjectName("alarm_clock_button")
        self.stop_watch_button = QtWidgets.QPushButton(self.menu)
        self.stop_watch_button.setGeometry(QtCore.QRect(135, 190, 230, 70))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.stop_watch_button.setFont(font)
        self.stop_watch_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.stop_watch_button.setObjectName("stop_watch_button")
        self.timer_button = QtWidgets.QPushButton(self.menu)
        self.timer_button.setGeometry(QtCore.QRect(135, 290, 230, 70))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.timer_button.setFont(font)
        self.timer_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.timer_button.setObjectName("timer_button")
        self.line_on_menu = QtWidgets.QFrame(self.menu)
        self.line_on_menu.setGeometry(QtCore.QRect(0, 150, 500, 30))
        self.line_on_menu.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_on_menu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_on_menu.setObjectName("line_on_menu")
        self.tasks_button = QtWidgets.QPushButton(self.menu)
        self.tasks_button.setGeometry(QtCore.QRect(135, 390, 230, 70))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.tasks_button.setFont(font)
        self.tasks_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.tasks_button.setObjectName("tasks_button")
        self.another_time_button = QtWidgets.QPushButton(self.menu)
        self.another_time_button.setGeometry(QtCore.QRect(135, 490, 230, 70))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.another_time_button.setFont(font)
        self.another_time_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.another_time_button.setObjectName("another_time_button")
        self.back_button_on_menu = QtWidgets.QPushButton(self.menu)
        self.back_button_on_menu.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.back_button_on_menu.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.back_button_on_menu.setText("")
        self.back_button_on_menu.setIcon(icon1)
        self.back_button_on_menu.setIconSize(QtCore.QSize(40, 35))
        self.back_button_on_menu.setObjectName("back_button_on_menu")
        self.stackedWidget.addWidget(self.menu)
        self.about_programme = QtWidgets.QWidget()
        self.about_programme.setObjectName("about_programme")
        self.back_ab_pr = QtWidgets.QPushButton(self.about_programme)
        self.back_ab_pr.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.back_ab_pr.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.back_ab_pr.setText("")
        self.back_ab_pr.setIcon(icon1)
        self.back_ab_pr.setIconSize(QtCore.QSize(40, 35))
        self.back_ab_pr.setObjectName("back_ab_pr")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.about_programme)
        self.scrollArea_2.setGeometry(QtCore.QRect(19, 79, 461, 501))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 442, 1018))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 1000))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color:  rgb(53, 59, 83);\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.label_about_pr = QtWidgets.QLabel(self.about_programme)
        self.label_about_pr.setGeometry(QtCore.QRect(155, 12, 190, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_about_pr.setFont(font)
        self.label_about_pr.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_about_pr.setObjectName("label_about_pr")
        self.stackedWidget.addWidget(self.about_programme)
        self.stopwatch = QtWidgets.QWidget()
        self.stopwatch.setObjectName("stopwatch")
        self.pushButton_start = QtWidgets.QPushButton(self.stopwatch)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 280, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    background-color: rgb(71, 255, 117);\n"
"    border-radius: 20px;\n"
"    border:5px solid rgb(85, 170, 0);\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(71, 255, 117);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.stopwatch)
        self.pushButton_stop.setGeometry(QtCore.QRect(350, 280, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 103, 96);\n"
"    border-radius: 20px;\n"
"    border:5px solid  rgb(170, 0, 0)\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(200, 103, 96);\n"
"    border:5px solid rgb(170, 0, 0)\n"
"}")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_write = QtWidgets.QPushButton(self.stopwatch)
        self.pushButton_write.setGeometry(QtCore.QRect(170, 250, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_write.setFont(font)
        self.pushButton_write.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_write.setObjectName("pushButton_write")
        self.pushButton_restart = QtWidgets.QPushButton(self.stopwatch)
        self.pushButton_restart.setGeometry(QtCore.QRect(170, 320, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.pushButton_restart.setFont(font)
        self.pushButton_restart.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 203, 97);\n"
"    border-radius: 20px;\n"
"    border:5px solid #aa8925\n"
"}\n"
"QPushButton: pressed {\n"
"    background-color: rgb(255, 153, 51);\n"
"        border:5px solid #aa8925\n"
"}")
        self.pushButton_restart.setObjectName("pushButton_restart")
        self.label_time_stopwatch = QtWidgets.QLabel(self.stopwatch)
        self.label_time_stopwatch.setGeometry(QtCore.QRect(30, 60, 441, 160))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(72)
        self.label_time_stopwatch.setFont(font)
        self.label_time_stopwatch.setStyleSheet("background-color: rgb(53, 59, 83);")
        self.label_time_stopwatch.setObjectName("label_time_stopwatch")
        self.textEdit_stopwhatch = QtWidgets.QTextEdit(self.stopwatch)
        self.textEdit_stopwhatch.setGeometry(QtCore.QRect(13, 380, 471, 211))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_stopwhatch.setFont(font)
        self.textEdit_stopwhatch.setStyleSheet("background-color: rgb(53, 59, 83);\n"
"font: 24pt \"Tahoma\";")
        self.textEdit_stopwhatch.setObjectName("textEdit_stopwhatch")
        self.pushButton_back_stopwatch = QtWidgets.QPushButton(self.stopwatch)
        self.pushButton_back_stopwatch.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.pushButton_back_stopwatch.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_back_stopwatch.setText("")
        self.pushButton_back_stopwatch.setIcon(icon1)
        self.pushButton_back_stopwatch.setIconSize(QtCore.QSize(40, 35))
        self.pushButton_back_stopwatch.setObjectName("pushButton_back_stopwatch")
        self.pushButton_home_stopwhatch = QtWidgets.QPushButton(self.stopwatch)
        self.pushButton_home_stopwhatch.setGeometry(QtCore.QRect(70, 10, 51, 41))
        self.pushButton_home_stopwhatch.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_home_stopwhatch.setText("")
        self.pushButton_home_stopwhatch.setIcon(icon2)
        self.pushButton_home_stopwhatch.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_home_stopwhatch.setObjectName("pushButton_home_stopwhatch")
        self.label_stopwach = QtWidgets.QLabel(self.stopwatch)
        self.label_stopwach.setGeometry(QtCore.QRect(165, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_stopwach.setFont(font)
        self.label_stopwach.setStyleSheet("background-color: rgb(255, 203, 97);\n"
"border:5px solid #aa8925")
        self.label_stopwach.setObjectName("label_stopwach")
        self.stackedWidget.addWidget(self.stopwatch)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Начать"))
        self.about_pr.setText(_translate("MainWindow", "О программе"))
        self.label_7.setText(_translate("MainWindow", "Универсальные часы-будильник"))
        self.label_on_tasks_2.setText(_translate("MainWindow", "Точное время:"))
        self.label_on_tasks_4.setText(_translate("MainWindow", "Дата:"))
        self.label_on_tasks_6.setText(_translate("MainWindow", "День недели:"))
        self.label_on_tasks.setText(_translate("MainWindow", "Заметки"))
        self.pushButton_save_task.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_load_task.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton_clear_task.setText(_translate("MainWindow", "Очистка"))
        self.comboBox_city.setItemText(0, _translate("MainWindow", "Выберите город"))
        self.comboBox_city.setItemText(1, _translate("MainWindow", "Москва"))
        self.comboBox_city.setItemText(2, _translate("MainWindow", "Санкт-Петербург"))
        self.comboBox_city.setItemText(3, _translate("MainWindow", "Калининград"))
        self.comboBox_city.setItemText(4, _translate("MainWindow", "Иркутск"))
        self.comboBox_city.setItemText(5, _translate("MainWindow", "Владивосток"))
        self.comboBox_city.setItemText(6, _translate("MainWindow", "Киев"))
        self.comboBox_city.setItemText(7, _translate("MainWindow", "Лондон"))
        self.comboBox_city.setItemText(8, _translate("MainWindow", "Сингапур"))
        self.comboBox_city.setItemText(9, _translate("MainWindow", "Нью-Йорк"))
        self.comboBox_city.setItemText(10, _translate("MainWindow", "Тель-Авив"))
        self.comboBox_city.setItemText(11, _translate("MainWindow", "Париж"))
        self.comboBox_city.setItemText(12, _translate("MainWindow", "Канберра"))
        self.comboBox_city.setItemText(13, _translate("MainWindow", "Джорджтаун"))
        self.comboBox_city.setItemText(14, _translate("MainWindow", "Сантьяго"))
        self.comboBox_city.setItemText(15, _translate("MainWindow", "Сиэтл"))
        self.comboBox_city.setItemText(16, _translate("MainWindow", "Рим"))
        self.comboBox_city.setItemText(17, _translate("MainWindow", "Берлин"))
        self.comboBox_city.setItemText(18, _translate("MainWindow", "Джакарта"))
        self.comboBox_city.setItemText(19, _translate("MainWindow", "Вашингтон"))
        self.comboBox_city.setItemText(20, _translate("MainWindow", "Токио"))
        self.comboBox_city.setItemText(21, _translate("MainWindow", "Пекин"))
        self.comboBox_city.setItemText(22, _translate("MainWindow", "Нью-Дели"))
        self.label_12.setText(_translate("MainWindow", "Время в других часовых поясах"))
        self.label_13.setText(_translate("MainWindow", "День недели:"))
        self.label_14.setText(_translate("MainWindow", "Дата:"))
        self.label_15.setText(_translate("MainWindow", "Время:"))
        self.label.setText(_translate("MainWindow", "Часы:"))
        self.label_3.setText(_translate("MainWindow", "Минуты:"))
        self.label_4.setText(_translate("MainWindow", "Секунды:"))
        self.pushButton_start_timer.setText(_translate("MainWindow", "Старт"))
        self.pushButton_restart_timer.setText(_translate("MainWindow", "Заново"))
        self.label_timer_label.setText(_translate("MainWindow", "00:00:00"))
        self.pushButton_stop_timer.setText(_translate("MainWindow", "Стоп"))
        self.label_timer.setText(_translate("MainWindow", "Таймер"))
        self.alarm_clock_button.setText(_translate("MainWindow", "Будильник"))
        self.stop_watch_button.setText(_translate("MainWindow", "Секундомер"))
        self.timer_button.setText(_translate("MainWindow", "Таймер"))
        self.tasks_button.setText(_translate("MainWindow", "Заметки"))
        self.another_time_button.setText(_translate("MainWindow", "Время др. час. поясов"))
        self.label_about_pr.setText(_translate("MainWindow", "О программе:"))
        self.pushButton_start.setText(_translate("MainWindow", "Старт"))
        self.pushButton_stop.setText(_translate("MainWindow", "Стоп"))
        self.pushButton_write.setText(_translate("MainWindow", "Запись"))
        self.pushButton_restart.setText(_translate("MainWindow", "Заново"))
        self.label_time_stopwatch.setText(_translate("MainWindow", "00:00:000"))
        self.textEdit_stopwhatch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_stopwach.setText(_translate("MainWindow", "Секундомер"))
